from datetime import datetime

POPULAR_DESTINATIONS = [
    {
        "id": "prague",
        "name": "Prague",
        "country": "Czech Republic",
        "region": "Central Europe",
        "description": "Historic city breaks with charming streets, beer culture and compact walking routes.",
        "tags": ["city", "culture", "architecture"],
        "travel_profile": ["culture", "architecture", "short trip"],
        "example_price_usd": 1000.0,
        "popular": True,
    },
    {
        "id": "budapest",
        "name": "Budapest",
        "country": "Hungary",
        "region": "Central Europe",
        "description": "Budget-friendly city with thermal baths, river views and lively evening scene.",
        "tags": ["city", "relax", "budget"],
        "travel_profile": ["spa", "city", "budget"],
        "example_price_usd": 950.0,
        "popular": True,
    },
    {
        "id": "romania_castles",
        "name": "Romania Castles",
        "country": "Romania",
        "region": "Eastern Europe",
        "description": "Wildcard route through castles, historic towns and low-cost transport options.",
        "tags": ["wildcard", "adventure", "culture"],
        "travel_profile": ["roadtrip", "culture", "low-cost"],
        "example_price_usd": 850.0,
        "popular": True,
    },
    {
        "id": "micro_tourism",
        "name": "Nearby Escape",
        "country": "Local",
        "region": "Domestic",
        "description": "Short rail or bus route to a nearby city with a hostel or glamping night.",
        "tags": ["micro-tourism", "budget", "nature"],
        "travel_profile": ["train", "weekend", "budget"],
        "example_price_usd": 250.0,
        "popular": True,
    },
]

SEED_PACKAGES = [
    {
        "package_id": "opt-001",
        "title": "Optimal choice: Prague for 7 days",
        "description": "Balanced flight and a good hotel in a popular city.",
        "direction": "Prague, Czech Republic",
        "days": 7,
        "total_price": 1000.0,
        "currency": "USD",
        "budget_breakdown": {
            "transport": 420.0,
            "accommodation": 330.0,
            "activities": 120.0,
            "local_transport": 80.0,
            "buffer": 50.0,
        },
        "fallback_level": 1,
        "tags": ["balance", "comfort", "europe"],
        "travel_type": "flight+hotel",
        "transport_summary": "One-stop flight, carry-on only.",
        "accommodation_summary": "4-star apartments near the Old Town.",
        "details": {
            "departure_date": datetime(2025, 8, 8),
            "return_date": datetime(2025, 8, 15),
            "flight": {
                "route": "MOW -> PRG",
                "type": "1 stop",
                "baggage": "carry-on only",
            },
            "hotel": {
                "name": "Hotel Royal Prague",
                "type": "hotel",
                "location": "city center",
                "stars": 4,
                "nights": 7,
            },
        },
        "cta": {
            "label": "Book now",
            "url": "https://affiliate.example.com/booking?package=opt-001",
        },
    },
    {
        "package_id": "comfort-001",
        "title": "Comfort focus: Budapest with spa",
        "description": "A calm trip with comfortable lodging and a short city program.",
        "direction": "Budapest, Hungary",
        "days": 7,
        "total_price": 950.0,
        "currency": "USD",
        "budget_breakdown": {
            "transport": 350.0,
            "accommodation": 370.0,
            "activities": 130.0,
            "local_transport": 70.0,
            "buffer": 30.0,
        },
        "fallback_level": 2,
        "tags": ["comfort", "relax", "europe"],
        "travel_type": "flight+hotel",
        "transport_summary": "Low-cost flight with hand luggage, hotel near thermal baths.",
        "accommodation_summary": "Comfortable 3-4 star hotel near the Danube.",
        "details": {
            "departure_date": datetime(2025, 8, 12),
            "return_date": datetime(2025, 8, 19),
            "flight": {
                "route": "MOW -> BUD",
                "type": "direct",
                "baggage": "carry-on only",
            },
            "hotel": {
                "name": "Danube Comfort Hotel",
                "type": "hotel",
                "location": "city center",
                "stars": 4,
                "nights": 7,
            },
        },
        "cta": {
            "label": "View details",
            "url": "https://affiliate.example.com/booking?package=comfort-001",
        },
    },
    {
        "package_id": "adventure-001",
        "title": "Adventure: Romania castles",
        "description": "A wildcard route with culture, history and inexpensive transport.",
        "direction": "Romania",
        "days": 10,
        "total_price": 850.0,
        "currency": "USD",
        "budget_breakdown": {
            "transport": 320.0,
            "accommodation": 280.0,
            "activities": 180.0,
            "local_transport": 50.0,
            "buffer": 20.0,
        },
        "fallback_level": 4,
        "tags": ["wildcard", "adventure", "culture"],
        "travel_type": "flight+hotel",
        "transport_summary": "Flight with one connection and local bus transfer.",
        "accommodation_summary": "Budget apartments and guesthouses outside the city.",
        "details": {
            "departure_date": datetime(2025, 8, 10),
            "return_date": datetime(2025, 8, 20),
            "flight": {
                "route": "MOW -> OTP",
                "type": "1 stop",
                "baggage": "carry-on only",
            },
            "hotel": {
                "name": "Castles Explorer Stay",
                "type": "guesthouse",
                "location": "Transylvania region",
                "stars": 3,
                "nights": 10,
            },
        },
        "cta": {
            "label": "Explore now",
            "url": "https://affiliate.example.com/booking?package=adventure-001",
        },
    },
    {
        "package_id": "micro-001",
        "title": "Micro-tourism: Nearby escape",
        "description": "A weekend escape by train or bus with a unique local stay.",
        "direction": "Local",
        "days": 2,
        "total_price": 250.0,
        "currency": "USD",
        "budget_breakdown": {
            "transport": 60.0,
            "accommodation": 120.0,
            "activities": 40.0,
            "local_transport": 20.0,
            "buffer": 10.0,
        },
        "fallback_level": 5,
        "tags": ["micro-tourism", "budget", "short trip"],
        "travel_type": "bus+hotel",
        "transport_summary": "Train or bus route to a nearby destination.",
        "accommodation_summary": "Cozy hostel or glamping night.",
        "details": {
            "departure_date": datetime(2025, 8, 15),
            "return_date": datetime(2025, 8, 17),
            "flight": {
                "route": "N/A",
                "type": "bus/train",
                "baggage": "carry-on only",
            },
            "hotel": {
                "name": "Forest Glamping Lodge",
                "type": "glamping",
                "location": "Nearby region",
                "stars": None,
                "nights": 2,
            },
        },
        "cta": {
            "label": "Book getaway",
            "url": "https://affiliate.example.com/booking?package=micro-001",
        },
    },
]
